export const EndPoints = {
    madarekSpotlight:"madarekspotlight",
    openChallenges:"openchallenges",
    ideaList:"idealist",
    bannerList:"rest/banner?language=ar",
    categories:"rest/categories",
    signUp : "signup",
    login : "login",
    expertInsights : "expertinsights",
    favouriteCategories : "usercategories",
    ideaLikeUnlike : "mylikedislike",
    challengeLikeUnlike : "mylikedislike",
    spotlightLikeUnlike : "mylikedislike",
    saveUserCategory:"saveusercategory",
    dashboard:"dashboard",
    getProfile:"getprofile",
    editProfile:"editprofile",
    countries: "rest/countries?language=ar",
    cities: "rest/cities?language=ar",
    notification:"notification",
    clearnotification:"clearnotification",
    logout:"logout",
    partner:"partners",
    expertInsightsList : "expertinsightslist",
    expertsInsiteDetail : "expertsinsitedetail",
}