import { baseUrl, isRTL } from "./Constant";
import { ARlabel, USlabel } from "./Messages";

export const Label = {
    HomeTitle: isRTL ? ARlabel._homeTitle : USlabel._homeTitle,
    SubnitIdea: isRTL ? ARlabel._subnitIdea : USlabel._subnitIdea,
    seeMore: isRTL ? ARlabel._seeMore : USlabel._seeMore,
    LogoTitle: isRTL ?  ARlabel._logoTitle : USlabel._logoTitle,
    Innovation: isRTL ?  ARlabel._innovation : USlabel._innovation,
    InnovationDetail: isRTL ? ARlabel._innovationDetail : USlabel._innovationDetail,
    NewWay: isRTL ? ARlabel._newWay : USlabel._newWay,
    SignInTitle: isRTL ? ARlabel._signInTitle : USlabel._signInTitle,
    MobileTitle: isRTL ? ARlabel._mobileTitle : USlabel._mobileTitle,
    Dot: isRTL ? ARlabel._dot : USlabel._dot,
    EmailTitle: isRTL ? ARlabel._emailTitle : USlabel._emailTitle,
    MobileNumber: isRTL ? ARlabel._mobileNumber : USlabel._mobileNumber,
    EmailAddress: isRTL ? ARlabel._emailAddress : USlabel._emailAddress,
    EnterOtpTitle: isRTL ? ARlabel._enterOtpTitle : USlabel._enterOtpTitle,
    GetText: isRTL ? ARlabel._getText : USlabel._getText,
    ResendOtpTitle: isRTL ? ARlabel._resendOtpTitle : USlabel._resendOtpTitle,
    ReceiveOtp: isRTL ? ARlabel._receiveOtp : USlabel._receiveOtp,
    UsePinTitle: isRTL ? ARlabel._usePinTitle : USlabel._usePinTitle,
    AddAccount: isRTL ? ARlabel._addAccount : USlabel._addAccount,
    GetAccount: isRTL ? ARlabel._getAccount : USlabel._getAccount,
    EnterPinTitle: isRTL ? ARlabel._enterPinTitle : USlabel._enterPinTitle,
    ForgotPassword: isRTL ? ARlabel._forgotPassword : USlabel._forgotPassword,
    UseOtpTitle: isRTL ? ARlabel.__useOtpTitle : USlabel.__useOtpTitle,
    ToLogin: isRTL ? ARlabel._toLogin : USlabel._toLogin,
    Email: isRTL ? ARlabel._email : USlabel._email,
    Phone: isRTL ? ARlabel._phone : USlabel._phone,
    Password: isRTL ? ARlabel._password : USlabel._password,
    Pin : isRTL ? ARlabel._pin : USlabel._pin,
    CatTitle: isRTL ? ARlabel._catTitle : USlabel._catTitle,
    Skip: isRTL ? ARlabel._skip : USlabel._skip,
    WhatdoyouPrefertosee: isRTL ? ARlabel._whatdoyouPrefertosee : USlabel._whatdoyouPrefertosee,
    Continue: isRTL ? ARlabel._continue : USlabel._continue,
    SignupTitle: isRTL ? ARlabel._signupTitle : USlabel._signupTitle,
    selectusertype: isRTL ? ARlabel._selectusertype : USlabel._selectusertype,
    individual: isRTL ? ARlabel._individual : USlabel._individual,
    corporate: isRTL ? ARlabel._corporate : USlabel._corporate,
    subjectexpert: isRTL ? ARlabel._subjectexpert : USlabel._subjectexpert,
    partner: isRTL ? ARlabel._partner : USlabel._partner,
    firstname: isRTL ? ARlabel._firstname : USlabel._firstname,
    lastname: isRTL ? ARlabel._lastname : USlabel._lastname,
    mobilenumber: isRTL ? ARlabel._mobilenumber : USlabel._mobilenumber,
    emailID: isRTL ? ARlabel._emailID : USlabel._emailID,
    password: isRTL ? ARlabel._password : USlabel._password,
    retypepassword: isRTL ? ARlabel._retypepassword : USlabel._retypepassword,
    enterfirstname: isRTL ? ARlabel._enterfirstname : USlabel._enterfirstname,
    enterlastname: isRTL ? ARlabel._enterlastname : USlabel._enterlastname,
    entermobilenumber: isRTL ? ARlabel._entermobilenumber : USlabel._entermobilenumber,
    enteremail: isRTL ? ARlabel._enteremail : USlabel._enteremail,
    enterpassword: isRTL ? ARlabel._enterpassword : USlabel._enterpassword,
    enterretypePassword: isRTL ? ARlabel._enterretypePassword : USlabel._enterretypePassword,
    enterSamePassword: isRTL ? ARlabel._enterSamePassword : USlabel._enterSamePassword,
    expertInsights: isRTL ? ARlabel._expertInsights : USlabel._expertInsights,
    viewAll: isRTL ? ARlabel._viewAll : USlabel._viewAll,
    renewableEnergy: isRTL ? ARlabel._renewableEnergy : USlabel._renewableEnergy,
    health: isRTL ? ARlabel._health : USlabel._health,
    education: isRTL ? ARlabel._education : USlabel._education,

    favouriteCategories: isRTL ? ARlabel._favouriteCategories : USlabel._favouriteCategories,

    constructionInfrastructure: isRTL ? ARlabel._constructionInfrastructure : USlabel._constructionInfrastructure,
    agricultureFisheriesy: isRTL ? ARlabel._agricultureFisheriesy : USlabel._agricultureFisheriesy,
    aviation: isRTL ? ARlabel._aviation : USlabel._aviation,
    informationTechnology: isRTL ? ARlabel._informationTechnology : USlabel._informationTechnology,

    readyToSubmitYourIdea: isRTL ? ARlabel._readyToSubmitYourIdea : USlabel._readyToSubmitYourIdea,
    submitIdea: isRTL ? ARlabel._submitIdea : USlabel._submitIdea,
    
  
    SignUpVerifyTitle: isRTL ? ARlabel._signUpVerifyTitle : USlabel._signUpVerifyTitle,
    VerifyNumber: isRTL ? ARlabel._verifyNumber : USlabel._verifyNumber,
    OneTimePinDetail: isRTL ? ARlabel._oneTimePinDetail : USlabel._oneTimePinDetail,
    OneTimePassword: isRTL ? ARlabel._oneTimePassword : USlabel._oneTimePassword,
    ToMessage: isRTL ? ARlabel._toMessage : USlabel._toMessage,
    DefaultPhoneCode: isRTL ? ARlabel._defaultPhoneCode : USlabel._defaultPhoneCode,
    VerifyTitle: isRTL ? ARlabel._verifyTitle : USlabel._verifyTitle,

    SocialLine: isRTL ? ARlabel._socialLine : USlabel._socialLine,
    IdeaDetails: isRTL ? ARlabel._ideaDetails : USlabel._ideaDetails,
    AcademyDetails: isRTL ? ARlabel._academyDetails : USlabel._academyDetails,
    Sector: isRTL ? ARlabel._sector : USlabel._sector,
    Category: isRTL ? ARlabel._category : USlabel._category,
    VoteNow: isRTL ? ARlabel._voteNow : USlabel._voteNow,
    Description: isRTL ? ARlabel._description : USlabel._description,
    Team: isRTL ? ARlabel._team : USlabel._team,
    Resources: isRTL ? ARlabel._resources : USlabel._resources,
    Video: isRTL ? ARlabel._video : USlabel._video,

}



